version: '3'
services:
  db:
    build: .
    image: ubuntusql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_USER=root
      # - PMA_PASSWORD=password
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db